name: Build EBW Redux for PR
on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload Fabric Mod
        uses: actions/upload-artifact@v4
        with:
          name: electroblobs-wizardry-redux-fabric-nightly.jar
          path: fabric/build/libs/electroblobs-wizardry-redux-*-fabric.jar

      - name: Upload Forge Mod
        uses: actions/upload-artifact@v4
        with:
          name: electroblobs-wizardry-redux-forge-nightly.jar
          path: forge/build/libs/electroblobs-wizardry-redux-*-forge.jar          